# Common build stage
FROM --platform=amd64 node:16-alpine3.14 as common-build-stage

COPY . ./app
RUN rm -rf /app/node_modules

WORKDIR /app
RUN yarn

EXPOSE ${PORT}

ARG NODE_ENV
ARG PORT
ARG SECRET_KEY
ARG TOKEN_EXPIRES_IN
ARG SENDGRID_API_KEY
ARG SENDER_EMAIL
ARG API_SECRET
ARG CREDENTIALS
ARG SOCKET_PORT
ARG JWT_SECRET
ARG OTP_EXPIRES_IN

# Development build stage
FROM common-build-stage as development-build-stage

ENV NODE_ENV development
ENV PORT=${PORT}
ENV SECRET_KEY=${SECRET_KEY}
ENV TOKEN_EXPIRES_IN=${TOKEN_EXPIRES_IN}
ENV SENDGRID_API_KEY=${SENDGRID_API_KEY}
ENV SENDER_EMAIL=${SENDER_EMAIL}
ENV API_SECRET=${API_SECRET}
ENV CREDENTIALS=${CREDENTIALS}
ENV SOCKET_PORT=${SOCKET_PORT}
ENV JWT_SECRET=${JWT_SECRET}
ENV OTP_EXPIRES_IN=${OTP_EXPIRES_IN}

CMD ["yarn", "run", "start:dev"]

# Production build stage
FROM common-build-stage as production-build-stage

ENV NODE_ENV production
ENV PORT=${PORT}
ENV SECRET_KEY=${SECRET_KEY}
ENV TOKEN_EXPIRES_IN=${TOKEN_EXPIRES_IN}
ENV SENDGRID_API_KEY=${SENDGRID_API_KEY}
ENV SENDER_EMAIL=${SENDER_EMAIL}
ENV API_SECRET=${API_SECRET}
ENV CREDENTIALS=${CREDENTIALS}
ENV SOCKET_PORT=${SOCKET_PORT}
ENV JWT_SECRET=${JWT_SECRET}
ENV OTP_EXPIRES_IN=${OTP_EXPIRES_IN}

CMD ["yarn", "run", "start"]
